### ISSUE TITLE
Popup cannot show properly

### ISSUE THREAD

**Issue by yujinlin0224** [aklinker1/vite-plugin-web-extension#102]
### Summary

Popup cannot show properly, with `Uncaught TypeError: can't access property "accept", (void 0) is undefined` error, same error to https://github.com/aklinker1/vite-plugin-web-extension/issues/99 but not sure is related or not

### Reproduction

https://github.com/aklinker1/vite-plugin-web-extension/tree/main/packages/demo-vue

https://user-images.githubusercontent.com/11353779/233687598-56fa9678-1d81-47c6-aeca-0e7d0ab3e260.mp4

### Environment

(Sorry that `envinfo` is failed to run with `'wmic' is not recognized as an internal or external command` error, probably [MS is removed wmic in Windows 11](https://winaero.com/microsoft-removed-the-wmic-tool-from-windows-11-dev-builds/).)
Microsoft Windows 11 Pro 22H2 64-bit (10.0.22621.1555)
npm: 9.5.0
node: 18.15.0
pnpm: 8.3.1
Run `demo-vue` project with Firefox Dev Edition 113.0b6 64-bit

**Comment by yujinlin0224** [comment]
Just test on Chromium-based browser llike Edge, same problem, content works but popup not.



https://user-images.githubusercontent.com/11353779/233808183-a2d3ddde-428d-423a-9635-883a406a99d9.mp4

**Comment by yujinlin0224** [comment]
@aklinker1, could you please let me know if you have been able to reproduce the issue?

**Comment by aklinker1** [comment]
I have not yet, sorry. I was busy last week. I'll try and get to it today or tomorrow.

**Comment by aklinker1** [comment]
I have not been able to repro with your setup, but I was able to on another, very large project, closed source project.

After sleeping on it, I might have a solution. I'll update this thread when I give it a go, probably later today.

**Comment by aklinker1** [comment]
Alright, I have a test version, it is working on the project that I could repro this error on.

@yujinlin0224 Can you try out `v3.0.7-alpha1`? It's the available using the `next` label on NPM:

```sh
pnpm i vite-plugin-web-extension@next
```

Or if you're still testing with the `packages/demo-vue` app, pull in the code from [this PR](https://github.com/aklinker1/vite-plugin-web-extension/pull/105) and run `pnpm dev`

**Comment by aklinker1** [comment]
Awesome, glad it's fixed. I'll get the PR merged, publish an update, and close this issue.
