### ISSUE TITLE
Using the svelte dev tools extension.

### ISSUE THREAD

**Issue by reedHam** [aklinker1/vite-plugin-web-extension#103]
Hi, 
Thanks for your hard work this is a great tool!

### Summary
I want to be able to use the svelte dev tools extension.

https://github.com/sveltejs/svelte-devtools

Currently it seems that any extensions installed for my chrome binary are not available when running my project in dev mode.

Any help would be appreciated.

**Comment by aklinker1** [comment]
You can install the dev tools in your regular chrome profile, then tell the plugin to use that profile instead:

```yml
# <project-root>/.webextrc.yml
chromiumProfile: "<absolute-path-to-chrome-profile>"
```

You can find your profile's path at `chrome://profile-internals`

To learn more, [check out the docs](https://vite-plugin-web-extension.aklinker1.io/guide/configure-browser-startup.html).
