### ISSUE TITLE
HMR doesn't work on Windows

### ISSUE THREAD

**Issue by ListenV** [aklinker1/vite-plugin-web-extension#107]
### Summary

When I modified the code, the page didn't change at all in DEV mode.

Watch mode is the same as well.

Or is it my fault?

My browser is Google Chrome and the version is `113.0.5672.93`.

### Environment

```
  System:
    OS: Windows 10 10.0.22621
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 5.39 GB / 15.94 GB
  Binaries:
    Node: 18.16.0 - D:\Development\Scoop\apps\nodejs-lts\current\node.EXE
    npm: 9.5.1 - D:\Development\Scoop\apps\nodejs-lts\current\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vite: ^4.3.5 => 4.3.5
    vite-plugin-web-extension: ^3.0.7 => 3.0.7
```

**Comment by aklinker1** [comment]
I need more info. Was it working on a previous version? Can you share a repo that I can reproduce the error on?

**Comment by ListenV** [comment]
I'm so sorry.
the repo file: [demo-vue.zip](https://github.com/aklinker1/vite-plugin-web-extension/files/11469654/demo-vue.zip)
and video: 

https://github.com/aklinker1/vite-plugin-web-extension/assets/45219522/04d9eb7c-e1f0-46c4-9cf7-df8222a3808d

**Comment by aklinker1** [comment]
No worries! Thanks for the info. I'll try and get to it this weekend... But the new Zelda game is out so we'll see lol.

**Comment by codingyu** [comment]
> No worries! Thanks for the info. I'll try and get to it this weekend... But the new Zelda game is out so we'll see lol.
🥲

**Comment by aklinker1** [comment]
@ListenV I cannot reproduce with the ZIP you sent me on mac.

https://github.com/aklinker1/vite-plugin-web-extension/assets/10101283/d0954f58-c7c1-4b3f-bb34-4f7b233875e7

That makes me think your version of Chrome is not above v110. HMR requires chrome v110 or above. Can you share your chrome version as well? I only see edge in the issue description.

https://github.com/aklinker1/vite-plugin-web-extension/assets/10101283/d45120e1-97c9-4247-aee5-aee46665bcab

If you want to test on Edge instead of Chrome, you can set the `chromiumBinary` path in your [`.webextrc.yml` file](https://vite-plugin-web-extension.aklinker1.io/guide/configure-browser-startup.html):

```yml
# ~/.webextrc.yml
chromiumBinary: C:\path\to\edge.exe
```

**Comment by aklinker1** [comment]
@codingyu Are you able to share your code?

**Comment by codingyu** [comment]
https://github.com/aklinker1/vite-plugin-web-extension/assets/20354841/96267f24-f4b7-4616-bf04-bd023a937667

@aklinker1

**Comment by codingyu** [comment]
https://github.com/aklinker1/vite-plugin-web-extension/assets/20354841/e5549538-6704-4ecd-9405-673269a8a5ba

@aklinker1

**Comment by ListenV** [comment]
I am like @codingyu, and there are no errors displayed in the console.
My Chrome Version is `113.0.5672.127` (Official Build) (64-bit). It's latest already and above v110.

### Env:
Win11
Google Chrome Version: 113.0.5672.127 (Official Build) (64-bit)
Node: v18.16.0
Vite: 4.3.8
Vue: 3.3.4
vite-plugin-web-extension: "3.0.7"

**Comment by aklinker1** [comment]
Fix released in [`v3.0.9`](https://github.com/aklinker1/vite-plugin-web-extension/releases/tag/v3.0.9)

**Comment by Honsal** [comment]
@aklinker1 It seems broken again. Even the project is default state, created by using `pnpm create vite-plugin-web-extension`

Windows 11 22H2 22621.1992
Lang: ko-KR
Line Endings: LF
Chrome 114.0.5735.199 (64 bit)


https://github.com/aklinker1/vite-plugin-web-extension/assets/13115858/3ed116f8-8c5e-4fec-82e7-c0036349f756

**Comment by Honsal** [comment]
#### Additional Condition

* React pages added by `UserOptions.additionalInputs` are also not working.
* Changing `content_scripts` related source file will reload extension But although extensions is reloaded, changes of `default_popup` and `UserOptions.additionalInputs` are not applied. Only changes of `content_scripts` is applied.
* Changing `background.service_worker` related sources' results are similar. HMR of background scripts work well unlike popup or additional inputs, BUT no other things updated.

If there's weird sentences so you cannot easily understand, please tell me. I am not native so i will pick some translator.
