### ISSUE TITLE
React SWC 3.3.1 does not work

### ISSUE THREAD

**Issue by aklinker1** [aklinker1/vite-plugin-web-extension#114]
If it can help future readers (I loose a few hours on this), upgrading `@vitejs/plugin-react-swc` from `3.2.0` to `3.3.1` broke the execution of the addons.

Popups are not rendered and in the console I get `React refresh runtime was loaded twice. Maybe you forgot the base path?` error.

_Originally posted by @stevebeauge in https://github.com/aklinker1/vite-plugin-web-extension/discussions/113_

**Comment by aklinker1** [comment]
Works with the basic template, closing this issue.

**Comment by ben-xD** [comment]
I have this issue too. Is there anything we can do to debug it?

**Comment by aklinker1** [comment]
@ben-xD if you can share your project with me, I can debug it. If not, check your app's logs and network requests to see if there are any errors, failed network requests, or lack of logs compared to a plain website project.

**Comment by Honsal** [comment]
in my case

`<script type="module" src="/src/pages/control-panel/index.tsx"></script>` showing same error with this post.

but `<script type="module" src="index.tsx"></script>` works.

However HMR is not working on second version. Maybe related to #107
