### ISSUE TITLE
Add Chromium's side_panel

### ISSUE THREAD

**Issue by JVariance** [aklinker1/vite-plugin-web-extension#131]
### Summary

It seems like Chromium's new [side_panel](https://developer.chrome.com/docs/extensions/reference/sidePanel/) is not supported and processed as of now. Could you please add it?

**Comment by JVariance** [comment]
I made a pull request!

**Comment by aklinker1** [comment]
Released in [`v3.2.0`](https://github.com/aklinker1/vite-plugin-web-extension/releases/tag/v3.2.0)
