### ISSUE TITLE
declarative_net_request support

### ISSUE THREAD

**Issue by Ily1606** [aklinker1/vite-plugin-web-extension#166]
### Summary

Can we're support declarative_net_request in manifest.json?

### Additional Context

(https://developer.chrome.com/docs/extensions/reference/api/declarativeNetRequest#type-ModifyHeaderInfo)

**Comment by Ily1606** [comment]
Oh, I'm sorry.

I think we can use /public directory.

![image](https://github.com/aklinker1/vite-plugin-web-extension/assets/40027165/29a452e1-39e2-4a26-92cf-2ed1a2762ee1)

**Comment by aklinker1** [comment]
Yup, putting the network rules in the public directory is the correct place 👍
