### ISSUE TITLE
Invalid TARGET Option for multibrowser support

### ISSUE THREAD

**Issue by GODrums** [aklinker1/vite-plugin-web-extension#171]
### Summary

When using the `TARGET=` option for multibrowser support, the execution fails. This command is used in the `package.json` to define the target browser.
Many demos in the official repository utilize it (see e.g. [demo-vue](https://github.com/aklinker1/vite-plugin-web-extension/blob/7b5bb377581ffd31f3b9ff44838c2e12ada0361c/packages/demo-vue/package.json)):
```bash
"build:firefox": "TARGET=firefox vite build --mode production"
```

Related documentation page: [Multibrowser Support - Manifest Templates](https://vite-plugin-web-extension.aklinker1.io/guide/supporting-multiple-browsers.html#manifest-templates)

The error:
```
'TARGET' is not recognized as an internal or external command,
operable program or batch file.
 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction (using one of the example projects)

Clone this repository:
```bash
git clone https://github.com/aklinker1/vite-plugin-web-extension.git
```
Navigate to one of the sample projects:
```bash
cd .\packages\demo-vue
```
Run the failing command:
```bash
pnpm run build:firefox
```

### Environment

```
  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 7800X3D 8-Core Processor
    Memory: 17.47 GB / 31.21 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.12.1 - ~\AppData\Roaming\npm\pnpm.CMD
    bun: 1.0.18 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (120.0.2210.91)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vite: ^5.0.0 => 5.0.2
    vite-plugin-web-extension: workspace:* => 4.1.0
```

**Comment by aklinker1** [comment]
@GODrums This is how you set an environment variable in Linux/Mac, it doesn't work on Windows, at least not in CMD and Powershell. It works with WSL and git bash.

Solution: `cross-env`

```sh
pnpm i cross-env
```

```diff
- "dev:firefox": "TARGET=Firefox vite",
+ "dev:firefox": "cross-env TARGET=Firefox vite",
```

I can add a section to the docs with this info.

**Comment by GODrums** [comment]
Thank you for the extensive explanation! Your suggested solution works exactly as intented.

I would love a short section about this for us Windows users, although I probably should have been able to figure this out myself.

**Comment by aklinker1** [comment]
Added docs in https://github.com/aklinker1/vite-plugin-web-extension/commit/830394587ef60ab6a3e19f41e7771bdabb2b4c80
