### ISSUE TITLE
In the default starter project modifying `src/popup.ts` closes the browser and never reopens it

### ISSUE THREAD

**Issue by antitoxic** [aklinker1/vite-plugin-web-extension#172]
### Summary

I created a empty starter project (vanilla ts) via `pnpm create vite-plugin-web-extension` and I modified `popup.ts` but the browser simply closed and never re-opened.

### Reproduction

- `pnpm create vite-plugin-web-extension`
- `pnpm install`
- `pnpm dev`
- Modify `src/popup.ts`
- Now the browser closes but never reopens. I also expected a change to `popup.ts` wouldn't cause a browser restart but simply HMR

### Environment

```
  System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M2 Pro
    Memory: 53.23 MB / 16.00 GB
    Shell: 3.6.4 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.15.0 - ~/pnpm/node
    npm: 9.5.0 - ~/pnpm/npm
    pnpm: 8.12.1 - ~/pnpm/pnpm
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 16.1
  npmPackages:
    vite: ^5.0.0 => 5.0.10
    vite-plugin-web-extension: ^4.0.0 => 4.1.0
```

**Comment by aklinker1** [comment]
Fixed in [`v4.1.1`](https://github.com/aklinker1/vite-plugin-web-extension/releases/tag/v4.1.`). Thanks for the report, let me know if it doesn't work for you 👍
