### ISSUE TITLE
Doesn't support WASM

### ISSUE THREAD

**Issue by michaelessiet** [aklinker1/vite-plugin-web-extension#176]
### Summary

I'm currently building a web extension that makes use of tiny-secp256k1 by bitcoinjs. Prior to making use of this all I had to add to my vite config was the vite-wasm-plugin and vite-plugin-top-level-await. However, this plugin isn't compatible with WASM in turn making it incompatible with vite-wasm-plugin.

Please is there a way around this? I have dropped the error screenshot below. The error seems to be about the bundle target being iife instead of es, but I set esnext as my target in the vite.config.js

![Screenshot 2024-01-06 at 19 14 54](https://github.com/aklinker1/vite-plugin-web-extension/assets/23281128/263ce8fc-b613-4bb8-b442-2a2ff6a46cd8)

### Environment

![Screenshot 2024-01-06 at 19 19 42](https://github.com/aklinker1/vite-plugin-web-extension/assets/23281128/5d7efe8e-1d94-4df7-a81c-39bffba2bd92)

**Comment by aklinker1** [comment]
Could you share a reproduction so I can look into this? I have minimal experience with wasm, and it would take a long time for me to _maybe_ reproduce this.

**Comment by devmattrick** [comment]
I also bumped into this, but I don't think this is related to wasm. It should happen anywhere you try to use top-level await, which is not supported by `iife` modules. I have a simple repro available [here](https://github.com/devmattrick/vite-webex-top-level-await-repro). 

Is there a reason to use `iife` here over `esm`? I haven't tested it, but I would guess recent browsers would support ESM in browser extension scripts?

**Comment by aklinker1** [comment]
I have a large PR in progress that adds an ESM mode for content scripts. Production builds are working, but dev mode is still a WIP.

See #357 and #584.
