### ISSUE TITLE
Cannot load extension with file or directory name _plugin-vue_export-helper.js. Filenames starting with "_" are reserved for use by the system. 无法加载清单。

### ISSUE THREAD

**Issue by chen-af** [aklinker1/vite-plugin-web-extension#178]
vue-tsc && vite build 完之后dist目录生成_plugin-vue_export-helper.js文件 然后谷歌浏览器扩展程序加载报错不识别_符号
![微信截图_20240126112321](https://github.com/aklinker1/vite-plugin-web-extension/assets/119917733/20192dd0-74fe-488f-974b-fb7d0af13a57)
Cannot load extension with file or directory name plugin-vue_export-helper.js. Filenames starting with "" are reserved for use by the system.
无法加载清单。
![image](https://github.com/aklinker1/vite-plugin-web-extension/assets/119917733/9a773fcb-092b-4654-bc97-f46683635788)

**Comment by aklinker1** [comment]
Please provide a reproduction
