### ISSUE TITLE
using firefox instead of chrome during dev builds

### ISSUE THREAD

**Issue by Yakiyo** [aklinker1/vite-plugin-web-extension#187]
Hi, during development i use `pnpm dev` command which opens up a new chrome instance for testing the extension. How would i configure it to open up firefox instead of chrome? i tried searching through the docs but couldn't find any thing on changing the browser. any help would be appreciated

**Comment by aklinker1** [comment]
The plugin accepts a `browser` option:

https://github.com/aklinker1/vite-plugin-web-extension/blob/9343f14f122b8a0a0b89176af0f83c8936177d67/packages/vite-plugin-web-extension/src/options.ts#L52-L57

I could have sworn this was documented somewhere... but I guess not? I couldn't find it in the docs either.

```ts
// vite.config.ts
export default defineConfig({
  plugins: [
    WebExtension({
      browser: process.env.TARGET_BROWSER,
    }),
  ],
});
```

Then run:

```sh
$ TARGET_BROWSER=firefox vite
```

**Comment by Yakiyo** [comment]
> ```ts
> // vite.config.ts
> export default defineConfig({
>   plugins: [
>     WebExtension({
>       browser: process.env.TARGET_BROWSER,
>     }),
>   ],
> });
> ```
that really helps. thanks a lot
