### ISSUE TITLE
Can't create project

### ISSUE THREAD

**Issue by chengfengfengwang** [aklinker1/vite-plugin-web-extension#189]
1. npm create vite-plugin-web-extension
2. enter arbitrary name
3. get error :

FetchError: [GET] "https://raw.githubusercontent.com/aklinker1/vite-plugin-web-extension/main/packages/create-vite-plugin-web-extension/templates/templates.json": <no response> fetch failed
cause: Error: connect ECONNREFUSED 0.0.0.0:443
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16) {
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '0.0.0.0',
      port: 443
    }

**Comment by aklinker1** [comment]
Project templates are hosted on Github, which can go down occasionally. When this happens, just try again later.
