### ISSUE TITLE
Upgrade Svelte version to v4

### ISSUE THREAD

**Issue by willdhorn** [aklinker1/vite-plugin-web-extension#194]
Currently, svelte projects are initialized using v3.55.1, despite v4 having been released last year

**Comment by willdhorn** [comment]
This is the diff of running `npx svelte-migrate@latest svelte-4` (as per [the migration guide](https://svelte.dev/docs/v4-migration-guide))
```diff
   "devDependencies": {
-    "@sveltejs/vite-plugin-svelte": "^2.0.3",
+    "@sveltejs/vite-plugin-svelte": "^2.4.1",
     "@tsconfig/svelte": "^3.0.0",
     "@types/webextension-polyfill": "^0.10.0",
-    "svelte": "^3.55.1",
-    "svelte-check": "^2.10.3",
+    "svelte": "^4.0.0",
+    "svelte-check": "^3.4.3",
     "tslib": "^2.5.0",
     "typescript": "^5.3.2",
     "vite": "^4.0.0",
     "vite-plugin-web-extension": "^4.0.0",
     "webextension-polyfill": "^0.10.0"
   }
```

**Comment by nileshtrivedi** [comment]
+1 

I created a new web extension project and was surprised that it was configured with Svelte 3.55 and Vite 4.0.

**Comment by nileshtrivedi** [comment]
I submitted a PR #200 for this. Please let me know if any other changes are needed to make this complete and ready to merge.

**Comment by aklinker1** [comment]
Nope, just getting the updated code to the main branch will make it available in the starter kit immediately! Thanks
