### ISSUE TITLE
Manifest cannot be read or something is missing

### ISSUE THREAD

**Issue by thiagolmoraes** [aklinker1/vite-plugin-web-extension#210]
### Summary

I followed the steps in this guide https://vite-plugin-web-extension.aklinker1.io/guide/  and after the installation was done I ran the command "npm run dev" and got this error message
 
![image](https://github.com/user-attachments/assets/0c4d3468-0f41-488f-9ef5-fc16970a0fe9)

"Error to loading extension" / "Manifest File cannot be read or is missing"

**Comment by oneezy** [comment]
what's your `manifest.json` look like?

this is working for me but having issue with hot reload:
```
{
  "{{chrome}}.manifest_version": 3,
  "{{firefox}}.manifest_version": 2,
  "icons": {
    "16": "icon/16.png",
    "32": "icon/32.png",
    "48": "icon/48.png",
    "96": "icon/96.png",
    "128": "icon/128.png"
  },
  "{{chrome}}.action": {
    "default_popup": "popup.html"
  },
  "{{firefox}}.browser_action": {
    "default_popup": "popup.html"
  },
  "background": {
    "{{chrome}}.service_worker": "background.js",
    "{{firefox}}.scripts": ["background.js"]
  },
  "content_scripts": [
    {
      "matches": ["*://*/*"],
      "js": ["src/scripts.js"],
      "css": ["src/styles.css"]
    }
  ]
}
```

**Comment by thiagolmoraes** [comment]
> what's your `manifest.json` look like?
> 
> this is working for me but having issue with hot reload:
> 
> ```
> {
>   "{{chrome}}.manifest_version": 3,
>   "{{firefox}}.manifest_version": 2,
>   "icons": {
>     "16": "icon/16.png",
>     "32": "icon/32.png",
>     "48": "icon/48.png",
>     "96": "icon/96.png",
>     "128": "icon/128.png"
>   },
>   "{{chrome}}.action": {
>     "default_popup": "popup.html"
>   },
>   "{{firefox}}.browser_action": {
>     "default_popup": "popup.html"
>   },
>   "background": {
>     "{{chrome}}.service_worker": "background.js",
>     "{{firefox}}.scripts": ["background.js"]
>   },
>   "content_scripts": [
>     {
>       "matches": ["*://*/*"],
>       "js": ["src/scripts.js"],
>       "css": ["src/styles.css"]
>     }
>   ]
> }
> ```

I'm sorry I forgot to post manifest. The manifest from src/ looks like 

```
{
  "{{chrome}}.manifest_version": 3,
  "{{firefox}}.manifest_version": 2,
  "icons": {
    "16": "icon/16.png",
    "32": "icon/32.png",
    "48": "icon/48.png",
    "96": "icon/96.png",
    "128": "icon/128.png"
  },
  "{{chrome}}.action": {
    "default_popup": "src/popup.html"
  },
  "{{firefox}}.browser_action": {
    "default_popup": "src/popup.html"
  },
  "background": {
    "{{chrome}}.service_worker": "src/background.ts",
    "{{firefox}}.scripts": ["src/background.ts"]
  }
}
```

Inside dist 

```{
    "name":"node22",
    "version":"1.0.0",
    "manifest_version":3,
    "icons":{"16":"icon/16.png","32":"icon/32.png","48":"icon/48.png","96":"icon/96.png","128":"icon/128.png"},
    "action":{"default_popup":"src/popup.html"},
    "background":{
        "service_worker":"src/background.js"
        },
        "host_permissions":["http://localhost/*"],
        "content_security_policy":
            {
                "extension_pages":"script-src 'self' 'wasm-unsafe-eval' http://localhost:*; object-src 'self';"
            }
        }
```

**Comment by aklinker1** [comment]
It looks like a problem with the "reload manager extension" that gets loaded along side your extension to handle reloads... Not a problem with your manifest.

**Comment by thiagolmoraes** [comment]
> It looks like a problem with the "reload manager extension" that gets loaded along side your extension to handle reloads... Not a problem with your manifest.

hm, how can I solve it?

**Comment by thiagolmoraes** [comment]
> No, sorry, never seen this before... Did you check to see if the directories mentioned exist? Are you using WSL?

hmm yeap, I'm using WSL

**Comment by oneezy** [comment]
i was using **git bash**. @aklinker1 you think it's OS specific issue?

**Comment by thiagolmoraes** [comment]
> i was using **git bash**. @aklinker1 you think it's OS specific issue?

Maybe its OS issue, using node directly on windows, its worked
![image](https://github.com/user-attachments/assets/4710a17b-1356-4bfb-bee9-9a2a0ddd1a5e)

**Comment by aklinker1** [comment]
Haha I just deleted my windows install, so glad you got it working!
