### ISSUE TITLE
Add support for @vitejs/plugin-react-swc

### ISSUE THREAD

**Issue by VladimirMikulic** [aklinker1/vite-plugin-web-extension#227]
### Summary

Add support for using @vitejs/plugin-react-swc instead of @vitejs/plugin-react

### Reproduction

1. npm create vite-plugin-web-extension
2. Replace @vitejs/plugin-react with @vitejs/plugin-react-swc
3. npm install
4. npm run dev
5. Get the error

[vite]: Rollup failed to resolve import "/@react-refresh" from "/project-path/src/popup.html?html-proxy&index=0.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

### Environment

```
System:
    OS: Linux 6.8 Ubuntu 24.04 LTS
    CPU: Redacted
    Memory: Redacted
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 22.11.0 - /usr/bin/node
    Yarn: 1.22.22 - ~/.yarn/bin/yarn
    npm: 10.8.0 - ~/.npm-global/bin/npm
    pnpm: 8.11.0 - ~/.npm-global/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.85
  npmPackages:
    vite: ^6.0.2 => 6.0.2 
    vite-plugin-web-extension: ^4.3.1 => 4.3.1
```

**Comment by aklinker1** [comment]
Did you try this? https://github.com/aklinker1/vite-plugin-web-extension/issues/84#issuecomment-1471196461

**Comment by VladimirMikulic** [comment]
Appreciate the fast response @aklinker1! Yes, that works!
