### ISSUE TITLE
HMR

### ISSUE THREAD

**Issue by sevensidedmarble** [aklinker1/vite-plugin-web-extension#23]
Hi,

I see that there's a problem with manifest v3 and this branch: https://github.com/aklinker1/vite-plugin-web-extension/pull/14

Nonetheless, maybe this could get merged in with just a way to turn it off for v3 for now? And once they fix the underlying bug in chrome it can be fully turned on for v3?

**Comment by aklinker1** [comment]
I'll see if I can get the PR cleaned up tonight, I don't remember how close it is to being ready.

**Comment by aklinker1** [comment]
This has been merged. The only thing you should have to do is change your scripts from

```bash
vite build --watch
```

to 

```bash
vite dev
```

And then it should just work. I wasn't able to testing this against a wide varity of projects, so if you have problems getting it up and running, feel free to re-open this issue

**Comment by sevensidedmarble** [comment]
Wow, thanks a ton, that was fast!
