### ISSUE TITLE
Vite 2.6.0 uses esbuild by default

### ISSUE THREAD

**Issue by ohmree** [aklinker1/vite-plugin-web-extension#24]
I'll start by thanking you for making this, it's a great plugin!

When building without specifying `build.minify = 'terser'` I get the following warning:
```
build.terserOptions is specified but build.minify is not set to use Terser. Note Vite now defaults to use esbuild for minification. If you still prefer Terser, set build.minify to "terser".
```
So the readme should probably mention that you should set `build.minify` to `'terser'`.

Sidenote: I've found that esbuild does a much better job at minifying my code (about 2x smaller), not sure if this is because it mangles names or if it's just better.
I think it's worth figuring out how to support esbuild in this plugin.

**Comment by aklinker1** [comment]
Interesting, I've seen that warning before, but I thought it was fixed. My extensions are running vite 2.6+, but I'm not seeing this message. I believe if you use vite 2.6+, it's defaulting to esbuild, not terser.

Do you have a small repo that reproduces this warning? Then I can fix it and add support for esbuild

**Comment by ohmree** [comment]
> Do you have a small repo that reproduces this warning? Then I can fix it and add support for esbuild

I'll try creating one based on my (non-open-source) project that's based on [`vitesse-webext`](https://github.com/antfu/vitesse-webext/), stay tuned.

**Comment by aklinker1** [comment]
Cool, thanks! I'll check it out and see what's up
