### ISSUE TITLE
js files not being loaded on watch mode

### ISSUE THREAD

**Issue by jibin2706** [aklinker1/vite-plugin-web-extension#27]
I tried running examples from the repo but the js files are giving 404 error (both chrome & firefox).

**Comment by aklinker1** [comment]
I'll look into this sometime this week. What OS are you using? Which commands are failing?

**Comment by jibin2706** [comment]
> I'll look into this sometime this week. What OS are you using? Which commands are failing?

Found the issue, the dev server was running on 3001 but the js file was being fetched with port 3000

**Comment by jibin2706** [comment]
> Ahh, ok, so you had another application running on 3000, so vite started up on 3001?

yes
