### ISSUE TITLE
Environement variables .env

### ISSUE THREAD

**Issue by flo-pereira** [aklinker1/vite-plugin-web-extension#29]
Hi,

Is there a way to get env variables from `.env` in content_script ?

.env
```
VITE_CUSTOM = test
```

vite.config.ts
```javascript
export default defineConfig((command, mode) => {
  console.log(command, mode);
  // { mode: 'development', command: 'serve' }
  
  console.log(loadEnv(mode, __dirname));
  // { VITE_CUSTOM: 'test' }
  ...
```

content_script.ts
```javascript
   console.log(import.meta.env)
//   {"BASE_URL":"/","MODE":"production","DEV":false,"PROD":true}
````

Thanks

**Comment by aklinker1** [comment]
I believe .env files are loaded from the root that is specified in the `vite.config.ts` file. In all the examples, I set that to `src/`. Check if your config specifies a root, and try putting the .env files there.

**Comment by flo-pereira** [comment]
You were right, that was just a problem with my root dir, sorry for that ! :pray:

**Comment by flo-pereira** [comment]
however, there is an issue that the .env file have to be in the `root` dir, seems that it doesn't take `envDir` path.

**Comment by flo-pereira** [comment]
got it

```
libModeViteConfig: {
  envDir: __dirname,
}
```
