### ISSUE TITLE
Publish a `create-vite-plugin-web-extension` package to bootstrap projects.

### ISSUE THREAD

**Issue by aklinker1** [aklinker1/vite-plugin-web-extension#46]
I'd like to be able to have a one-liner for configuring a new project:

```bash
npm  create vite-plugin-web-extension [template]
yarn create vite-plugin-web-extension [template]
pnpm create vite-plugin-web-extension [template]
```

There can be a couple of different templates to get started with:

| Javascript | Typescript |
| :-: | :-: |
| vanilla | vanilla-ts |
| vue | vue-ts |
| react | react-ts |

**Comment by fhefh2015** [comment]
Need it and look forward to using it sooner
