### ISSUE TITLE
Error: You must supply options.input to rollup

### ISSUE THREAD

**Issue by Cihatata** [aklinker1/vite-plugin-web-extension#62]
Hi,

I am using `vite-plugin-web-extension v1`. Firstly i removed this line`"default_popup": "popup.html` from `manifest.json` then i run build command and Vite threw error.
`Error: You must supply options.input to rollup`

if i add `popup.html` again to manifest.json. There is no problem. 

i dont want to use popup. How to remove it ? 

how do i fix this problem ?

Error log 
<img width="713" alt="image" src="https://user-images.githubusercontent.com/38289027/214048699-bc858b95-8627-4463-b6e8-15ecd5a92165.png">

My manifest
```js
{
  "manifest_version": 3,
  "name": "Resmo Chrome Extension",
  "$schema": "https://json.schemastore.org/chrome-manifest.json",
  "description": "",
  "version": "1.0",
  "background": {
    "service_worker": "only_background.js"
  },
  "icons": {
    "16": "public/images/icon-16.png",
    "32": "public/images/icon-32.png",
    "48": "public/images/icon-48.png",
    "128": "public/images/icon-128.png"
  },
  "action": {
    "default_icon": {
      "16": "public/images/icon-16.png",
      "32": "public/images/icon-32.png"
    },
    "default_title": "Click to view a popup"
  },
  "permissions": [
    "alarms",
    "identity",
    "identity.email",
    "scripting",
    "storage",
    "tabs",
    "webRequest",
    "declarativeNetRequest",
    "declarativeWebRequest",
    "*://*/*"
  ],
  "host_permissions": [
    "http://*/*",
    "https://*/*"
  ],
  "content_scripts": [
    {
      "matches": [
        "http://*/*",
        "https://*/*"
      ],
      "js": [
        "contentScript.js"
      ]
    }
  ],
  "content_security_policy": {
    "extension_pages": "script-src 'self'; object-src 'self'"
  }
}
```

**Comment by aklinker1** [comment]
See #10 and #40. V2 will support extensions without a UI, but right now you need at least 1 html file.

Here's a work around for now: https://github.com/aklinker1/vite-plugin-web-extension/issues/10#issuecomment-1089367768

**Comment by Cihatata** [comment]
Okey, thank you. I'm looking forward to the new version.
