### ISSUE TITLE
Vite 4 Support

### ISSUE THREAD

**Issue by aklinker1** [aklinker1/vite-plugin-web-extension#67]
Discovered while working on v2, Vite 4 does not work with the plugin. Once V2 is merged, look into supporting Vite 4.

**Comment by MikeDaniel18** [comment]
What's the ETA on this? Happy to help with this.

**Comment by aklinker1** [comment]
I'm working on it right now, but the type changes will result in a breaking change, so I'm gonna try and get v3 out sometime this weekend.
