### ISSUE TITLE
Scripts missing when rebuilding HTML on Watch Mode

### ISSUE THREAD

**Issue by ChrRubin** [aklinker1/vite-plugin-web-extension#7]
When using `vite build --watch`, making changes to HTML files (whether vanilla HTML or via frameworks like Vue) will trigger a rebuild, but only HTML pages are rebuilt, causing all content and background scripts to be missing from the output folder until the command is run again. 

This can be reproduced on both the vanilla and vue demos included in the repo.

**Comment by aklinker1** [comment]
Thanks for the report, I had manually worked around this in one of my personal extensions by setting `build.emptyOutDir` to `false`, and manually deleting it with `fs.rmdirSync("dist", { recursive: true });`.

As of [`v1.0.5`](https://github.com/aklinker1/vite-plugin-web-extension/releases/tag/v1.0.5), this is done automatically for you when you pass `build.emptyOutDir = true`! Let me know if it doesn't work for you

**Comment by aklinker1** [comment]
Fixed by https://github.com/aklinker1/vite-plugin-web-extension/commit/a9642ce62c6a4611a5a49e8479c78f52653bb885
